# Gosec security scanner configuration
# https://github.com/securego/gosec

global:
  # Scan tests as well as production code
  tests: true

  # Audit mode: report all issues without suppression
  audit: false

  # Exclude rules (add rule IDs here if needed)
  # Common rules to consider excluding:
  # - G104: Audit errors not checked (can be noisy)
  # - G307: Poor file permissions when creating files (755/644 instead of 600)
  exclude:
    # Uncomment if too noisy during initial rollout:
    # - G104

  # Exclude generated code from scanning
  exclude-generated: true

  # Exclude directories from scanning
  exclude-dirs:
    - vendor
    - dist
    - zig-out
    - zig-cache
    - lib/guillotine-mini/zig-out
    - lib/guillotine-mini/zig-cache

# Severity thresholds
# Options: low, medium, high
severity: medium
confidence: medium

# Rule-specific configuration
# Each rule can have specific settings

# Rule configuration examples:
# G302: Expect file permissions to be 0600 or more restrictive
# Skip this check in test files where temp files are common
rules:
  G302:
    # Don't flag file permission issues in tests
    skip-tests: true

  # G304: File path provided as taint input
  # Skip in tests where we test various file operations
  G304:
    skip-tests: true

  # G204: Audit use of command execution (subprocess)
  # Skip in tests where we test command execution
  G204:
    skip-tests: true

  # G404: Use of weak random number generator (math/rand)
  # Skip in tests where crypto-strength randomness isn't needed
  G404:
    skip-tests: true

# Output format options
# Available formats: json, yaml, csv, junit-xml, html, sonarqube, golint, sarif, text
# format: text

# Maximum issues to report (0 = unlimited)
# max-issues: 0

# Concurrency level for analysis
# concurrency: 2
